name: Auto Update BTC/Gold Graph

on:
  schedule:
    - cron: '0 8 * * *'  # каждый день в 08:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install matplotlib numpy pandas yfinance

    - name: Show current dir and files
      run: |
        pwd
        ls -la

    - name: Run BTC/Gold forecast script
      run: python btc2gold_plus5years.py

    - name: Commit and push updated graph
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add btc_gold_forecast.png
        git commit -m "Auto update BTC/Gold forecast graph"
        git push
      continue-on-error: true
